# Generated by Django 6.0 on 2025-12-17 07:13

import app.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', app.manager.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='create_at',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, verbose_name='word count'),
        ),
    ]
